In [176]:
# importing pandas and numpy

import pandas as pd
import numpy as np

In [177]:

books = pd.read_csv('data.csv')

In [175]:
books.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0

In [178]:
books.shape

(6810, 12)

In [179]:
books.head(1)

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0

In [180]:
# filtering for main columns
#isbn13
#title
#subtitle
#authors
#categories
#description

books = books[['isbn13','title','subtitle','authors','categories','description']]
books.head()

,isbn13,title,subtitle,authors,categories,description
0,9780002005883,Gilead,NaN,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...
1,9780002261982,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...
2,9780006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...
3,9780006178736,Rage of angels,NaN,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b..."
4,9780006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...

In [181]:
books.shape

(6810, 6)

In [182]:
# checking non null colums
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 6 columns):
isbn13         6810 non-null int64
title          6810 non-null object
subtitle       2381 non-null object
authors        6738 non-null object
categories     6711 non-null object
description    6548 non-null object
dtypes: int64(1), object(5)
memory usage: 319.3+ KB

In [183]:
#checking null colums
books.isnull().sum()

isbn13            0
title             0
subtitle       4429
authors          72
categories       99
description     262
dtype: int64

In [184]:
non_null_values = books['subtitle'].dropna()
non_null_values.head(100)

1                                                A Novel
7         A History of the Indian Ocean and Its Invaders
8                                        Chaos and Order
25                            The Complete Short Stories
34                                              A Memoir
                             ...
252                                              A Novel
256    An Insider's Guide to the Body that Will Make ...
263                                 A Story of Detection
264                                              Stories
265    A Novel of a Flamboyant Woman Who Risked All f...
Name: subtitle, Length: 100, dtype: object

In [185]:
# dropping null description
books= books.dropna(subset=['description'])
books.reset_index(drop = True,inplace = True )

In [186]:
books.shape

(6548, 6)

In [187]:
# fill in the missing values
books['authors'] = books['authors'].fillna('Unknown Author')
books['categories'] = books['categories'].fillna('Unknown Category')

In [188]:
# dropping the subtitle column due to missing values
books.drop(columns=['subtitle'], inplace=True)

In [189]:
books.shape

(6548, 5)

In [190]:
# verifying the null values 
books.isnull().sum()

isbn13         0
title          0
authors        0
categories     0
description    0
dtype: int64

In [192]:
# checking duplicatres

books[books.duplicated()]

Empty DataFrame
Columns: [isbn13, title, authors, categories, description]
Index: []

In [193]:
# verifying duplicates

books.duplicated().sum()

0

In [194]:
# cleaned df

books.head()

,isbn13,title,authors,categories,description
0,9780002005883,Gilead,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...
1,9780002261982,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...
2,9780006163831,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...
3,9780006178736,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b..."
4,9780006280897,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...

In [195]:
# checking value
books.iloc[336].title

'Success Stories'

In [196]:
books.head()

,isbn13,title,authors,categories,description
0,9780002005883,Gilead,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...
1,9780002261982,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...
2,9780006163831,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...
3,9780006178736,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b..."
4,9780006280897,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...

In [197]:
 # Splitting into a list of strings
    
books['authors'] = books['authors'].apply(lambda x: x.split())

In [198]:
 # Splitting into a list of strings
    
books['categories'] = books['categories'].apply(lambda x: x.split())

In [199]:
 # Splitting into a list of strings
    
books['description'] = books['description'].apply(lambda x: x.split())

In [200]:
books.head(10)

,isbn13,title,authors,categories,description
0,9780002005883,Gilead,"[Marilynne, Robinson]",[Fiction],"[A, NOVEL, THAT, READERS, and, critics, have, ..."
1,9780002261982,Spider's Web,"[Charles, Osborne;Agatha, Christie]","[Detective, and, mystery, stories]","[A, new, 'Christie, for, Christmas', --, a, fu..."
2,9780006163831,The One Tree,"[Stephen, R., Donaldson]","[American, fiction]","[Volume, Two, of, Stephen, Donaldson's, acclai..."
3,9780006178736,Rage of angels,"[Sidney, Sheldon]",[Fiction],"[A, memorable,, mesmerizing, heroine, Jennifer..."
4,9780006280897,The Four Loves,"[Clive, Staples, Lewis]","[Christian, life]","[Lewis', work, on, the, nature, of, love, divi..."
5,9780006280934,The Problem of Pain,"[Clive, Staples, Lewis]","[Christian, life]","[""In, The, Problem, of, Pain,, C.S., Lewis,, o..."
6,9780006353287,An Autobiography,"[Agatha, Christie]","[Authors,, English]",[Donation.]
7,9780006380832,Empires of the Monsoon,"[Richard, Hall]","[Africa,, East]","[Until, Vasco, da, Gama, discovered, the, sea-..."
8,9780006470229,The Gap Into Madness,"[Stephen, R., Donaldson]","[Hyland,, Morn, (Fictitious, character)]","[A, new-cover, reissue, of, the, fourth, book,..."
9,9780006472612,Master of the Game,"[Sidney, Sheldon]","[Adventure, stories]","[Kate, Blackwell, is, an, enigma, and, one, of..."

In [201]:
# Making a large list of all the three lists combined

books['tag'] = books['authors'] + books['categories'] + books['description']

In [202]:
# Df with added column tag

books

,isbn13,title,authors,categories,description,tag
0,9780002005883,Gilead,"[Marilynne, Robinson]",[Fiction],"[A, NOVEL, THAT, READERS, and, critics, have, ...","[Marilynne, Robinson, Fiction, A, NOVEL, THAT,..."
1,9780002261982,Spider's Web,"[Charles, Osborne;Agatha, Christie]","[Detective, and, mystery, stories]","[A, new, 'Christie, for, Christmas', --, a, fu...","[Charles, Osborne;Agatha, Christie, Detective,..."
2,9780006163831,The One Tree,"[Stephen, R., Donaldson]","[American, fiction]","[Volume, Two, of, Stephen, Donaldson's, acclai...","[Stephen, R., Donaldson, American, fiction, Vo..."
3,9780006178736,Rage of angels,"[Sidney, Sheldon]",[Fiction],"[A, memorable,, mesmerizing, heroine, Jennifer...","[Sidney, Sheldon, Fiction, A, memorable,, mesm..."
4,9780006280897,The Four Loves,"[Clive, Staples, Lewis]","[Christian, life]","[Lewis', work, on, the, nature, of, love, divi...","[Clive, Staples, Lewis, Christian, life, Lewis..."
...,...,...,...,...,...,...
6543,9788173031014,Journey to the East,"[Hermann, Hesse]","[Adventure, stories]","[This, book, tells, the, tale, of, a, man, who...","[Hermann, Hesse, Adventure, stories, This, boo..."
6544,9788179921623,The Monk Who Sold His Ferrari: A Fable About F...,"[Robin, Sharma]","[Health, &, Fitness]","[Wisdom, to, Create, a, Life, of, Passion,, Pu...","[Robin, Sharma, Health, &, Fitness, Wisdom, to..."
6545,9788185300535,I Am that,"[Sri, Nisargadatta, Maharaj;Sudhakar, S., Diks...",[Philosophy],"[This, collection, of, the, timeless, teaching...","[Sri, Nisargadatta, Maharaj;Sudhakar, S., Diks..."
6546,9789027712059,The Berlin Phenomenology,"[Georg, Wilhelm, Friedrich, Hegel]",[History],"[Since, the, three, volume, edition, ofHegel's...","[Georg, Wilhelm, Friedrich, Hegel, History, Si..."
6547,9789042003408,'I'm Telling You Stories',"[Helena, Grice;Tim, Woods]","[Literary, Criticism]","[This, is, a, jubilant, and, rewarding, collec...","[Helena, Grice;Tim, Woods, Literary, Criticism..."

In [203]:
# creating a new df new_books keeping only two columns from the original df books

new_books = books[['isbn13','title' , 'tag']]
new_books

,isbn13,title,tag
0,9780002005883,Gilead,"[Marilynne, Robinson, Fiction, A, NOVEL, THAT,..."
1,9780002261982,Spider's Web,"[Charles, Osborne;Agatha, Christie, Detective,..."
2,9780006163831,The One Tree,"[Stephen, R., Donaldson, American, fiction, Vo..."
3,9780006178736,Rage of angels,"[Sidney, Sheldon, Fiction, A, memorable,, mesm..."
4,9780006280897,The Four Loves,"[Clive, Staples, Lewis, Christian, life, Lewis..."
...,...,...,...
6543,9788173031014,Journey to the East,"[Hermann, Hesse, Adventure, stories, This, boo..."
6544,9788179921623,The Monk Who Sold His Ferrari: A Fable About F...,"[Robin, Sharma, Health, &, Fitness, Wisdom, to..."
6545,9788185300535,I Am that,"[Sri, Nisargadatta, Maharaj;Sudhakar, S., Diks..."
6546,9789027712059,The Berlin Phenomenology,"[Georg, Wilhelm, Friedrich, Hegel, History, Si..."
6547,9789042003408,'I'm Telling You Stories',"[Helena, Grice;Tim, Woods, Literary, Criticism..."

In [204]:
# Converting tag column from list of strings to strings 

new_books['tag'] = new_books['tag'].apply(lambda x :" ".join(x))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [205]:
# Final df

new_books

,isbn13,title,tag
0,9780002005883,Gilead,Marilynne Robinson Fiction A NOVEL THAT READER...
1,9780002261982,Spider's Web,Charles Osborne;Agatha Christie Detective and ...
2,9780006163831,The One Tree,Stephen R. Donaldson American fiction Volume T...
3,9780006178736,Rage of angels,"Sidney Sheldon Fiction A memorable, mesmerizin..."
4,9780006280897,The Four Loves,Clive Staples Lewis Christian life Lewis' work...
...,...,...,...
6543,9788173031014,Journey to the East,Hermann Hesse Adventure stories This book tell...
6544,9788179921623,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma Health & Fitness Wisdom to Create...
6545,9788185300535,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit P...
6546,9789027712059,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel History Since th...
6547,9789042003408,'I'm Telling You Stories',Helena Grice;Tim Woods Literary Criticism This...

In [206]:
new_books['tag'][200]

'Paulo Coelho Fiction Eleven Minutes is the story of Maria, a young girl from a Brazilian village, whose first innocent brushes with love leave her heartbroken. At a tender age, she becomes convinced that she will never find true love, instead believing that "love is a terrible thing that will make you suffer. . . ." A chance meeting in Rio takes her to Geneva, where she dreams of finding fame and fortune. Maria\'s despairing view of love is put to the test when she meets a handsome young painter. In this odyssey of self-discovery, Maria has to choose between pursuing a path of darkness -- sexual pleasure for its own sake -- or risking everything to find her own "inner light" and the possibility of sacred sex, sex in the context of love. This P.S. edition features an extra 16 pages of insights into the book, including author interviews, recommended reading, and more.'

In [207]:
#Converting all the letters into lowercase  

new_books['tag'] = new_books['tag'].apply(lambda x :x.lower())

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [208]:
new_books['tag'][500]

'laura ingalls wilder juvenile fiction join the ingalls family as they celebrate little laura’s fifth birthday in the big woods of wisconsin. there are special presents from everyone, and that night laura falls asleep to the merry music of pa’s fiddle. renée graef’s enchanting full-color illustrations, inspired by garth williams’s classic artwork, bring laura and her family lovingly to life in our tenth my first little house book, adapted from laura ingalls wilder’s beloved storybooks. it’s a little house birthday to remember!'

In [209]:
new_books

,isbn13,title,tag
0,9780002005883,Gilead,marilynne robinson fiction a novel that reader...
1,9780002261982,Spider's Web,charles osborne;agatha christie detective and ...
2,9780006163831,The One Tree,stephen r. donaldson american fiction volume t...
3,9780006178736,Rage of angels,"sidney sheldon fiction a memorable, mesmerizin..."
4,9780006280897,The Four Loves,clive staples lewis christian life lewis' work...
...,...,...,...
6543,9788173031014,Journey to the East,hermann hesse adventure stories this book tell...
6544,9788179921623,The Monk Who Sold His Ferrari: A Fable About F...,robin sharma health & fitness wisdom to create...
6545,9788185300535,I Am that,sri nisargadatta maharaj;sudhakar s. dikshit p...
6546,9789027712059,The Berlin Phenomenology,georg wilhelm friedrich hegel history since th...
6547,9789042003408,'I'm Telling You Stories',helena grice;tim woods literary criticism this...

In [210]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features =5000 , stop_words = 'english')

In [211]:
# Converting into vectors

vectors = cv.fit_transform(new_books['tag']).toarray()

In [212]:
vectors[3000]

array([0, 0, 0, ..., 0, 0, 0])

In [213]:
len(cv.get_feature_names())

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

5000

In [214]:
# Getting separate list of words

cv.get_feature_names()

['000',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '150',
 '16',
 '17',
 '18',
 '1914',
 '1920s',
 '1929',
 '1930s',
 '1940',
 '1940s',
 '1945',
 '1950s',
 '1960s',
 '1962',
 '1970',
 '1970s',
 '1978',
 '1980s',
 '1984',
 '1986',
 '1987',
 '1989',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1994',
 '1995',
 '1996',
 '1998',
 '1999',
 '19th',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2005',
 '20th',
 '21',
 '21st',
 '22',
 '24',
 '25',
 '250',
 '30',
 '300',
 '35',
 '40',
 '400',
 '50',
 '500',
 '60',
 '75',
 'aaron',
 'abandoned',
 'abbey',
 'abby',
 'abe',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abraham',
 'abroad',
 'absolutely',
 'abstract',
 'abuse',
 'academy',
 'accept',
 'acceptance',
 'accepted',
 'accepts',
 'access',
 'accessible',
 'accident',
 'accidentally',
 'accidents',
 'acclaim',
 'acclaimed',
 'accompanied',
 'accompanies',
 'accompany',
 'accompanying',
 'accomplished',
 'accomplishments',
 'according',
 'account',
 'accounts',
 'accurate',
 'accurately',
 'accused',
 'achieve',
 'achievement',
 'achievements',
 'act',
 'acting',
 'action',
 'actions',
 'active',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'ad',
 'adam',
 'adams',
 'adaptation',
 'adapted',
 'add',
 'added',
 'addiction',
 'addition',
 'additional',
 'address',
 'addressed',
 'addresses',
 'administration',
 'admired',
 'adolescence',
 'adopted',
 'adult',
 'adultery',
 'adults',
 'advanced',
 'advantage',
 'adventure',
 'adventures',
 'advice',
 'aeschylus',
 'aesthetic',
 'aesthetics',
 'affair',
 'affairs',
 'affect',
 'affected',
 'afford',
 'affordable',
 'afraid',
 'africa',
 'african',
 'afterlife',
 'aftermath',
 'afterword',
 'agatha',
 'age',
 'aged',
 'agency',
 'agent',
 'agents',
 'ages',
 'aggressive',
 'aging',
 'ago',
 'ahead',
 'aid',
 'aids',
 'air',
 'al',
 'ala',
 'alan',
 'alanna',
 'albert',
 'alchemist',
 'alcott',
 'aldous',
 'alex',
 'alexander',
 'alfred',
 'alice',
 'alien',
 'aliens',
 'alighieri',
 'alike',
 'alison',
 'alive',
 'allan',
 'allen',
 'alliance',
 'allies',
 'allow',
 'allowed',
 'allows',
 'alongside',
 'alter',
 'altered',
 'alternate',
 'alternative',
 'amano',
 'amateur',
 'amazing',
 'ambition',
 'ambitions',
 'ambitious',
 'amelia',
 'america',
 'american',
 'americans',
 'amid',
 'amidst',
 'amis',
 'amusing',
 'amy',
 'analyses',
 'analysis',
 'analyzes',
 'ancient',
 'anderson',
 'andrew',
 'andrews',
 'andy',
 'anecdotes',
 'angel',
 'angela',
 'angeles',
 'anger',
 'anguish',
 'animal',
 'animals',
 'anita',
 'ann',
 'anna',
 'anne',
 'annie',
 'anniversary',
 'annotated',
 'annual',
 'anonymous',
 'answer',
 'answered',
 'answers',
 'anthology',
 'anthony',
 'anti',
 'antiques',
 'antiquity',
 'anton',
 'apart',
 'apartment',
 'apocalyptic',
 'apparent',
 'appeal',
 'appear',
 'appearance',
 'appeared',
 'appears',
 'apple',
 'application',
 'applications',
 'applied',
 'apply',
 'appointed',
 'appreciate',
 'apprentice',
 'approach',
 'approaches',
 'april',
 'aquinas',
 'arab',
 'archaeologist',
 'architect',
 'architecture',
 'archives',
 'arctic',
 'arden',
 'area',
 'areas',
 'aren',
 'argues',
 'arguing',
 'argument',
 'arguments',
 'aristocratic',
 'aristophanes',
 'aristotle',
 'arkansas',
 'armed',
 'armies',
 'arms',
 'armstrong',
 'army',
 'arranged',
 'array',
 'arrival',
 'arrived',
 'arrives',
 'arrogant',
 'art',
 'arthur',
 'articles',
 'artist',
 'artistic',
 'artists',
 'arts',
 'artwork',
 'asia',
 'asian',
 'aside',
 'asimov',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspect',
 'aspects',
 'aspiring',
 'assassin',
 'assassination',
 'assassins',
 'assault',
 'assignment',
 'assist',
 'assistant',
 'association',
 'astonishing',
 'astronomy',
 'asylum',
 'athens',
 'atlantic',
 'atlantis',
 'atmosphere',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempted',
 'attempting',
 'attempts',
 'attend',
 'attention',
 'attitude',
 'attitudes',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'atwood',
 'audience',
 'august',
 'augustine',
 'aunt',
 'austen',
 'auster',
 'australia',
 'authentic',
 'author',
 'authoritative',
 'authorities',
 'authority',
 'authors',
 'autobiographical',
 'autobiography',
 'available',
 'average',
 'avoid',
 'awaited',
 'awaits',
 'awakening',
 'awakens',
 'award',
 'awards',
 'aware',
 'awareness',
 'away',
 'awesome',
 'babies',
 'baby',
 'bach',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'baggins',
 'baker',
 'balance',
 'balanced',
 'baldwin',
 'ball',
 'ballet',
 'band',
 'bang',
 'bank',
 'banks',
 'banned',
 'bar',
 'barbara',
 'barely',
 'barker',
 'barnes',
 'barney',
 'barry',
 'bars',
 'barth',
 'base',
 'baseball',
 'based',
 'basic',
 'basis',
 'battle',
 'battles',
 'baudrillard',
 'baxter',
 'bay',
 'bc',
 'bce',
 'beach',
 'bear',
 'bears',
 'beast',
 'beat',
 'beatles',
 'beatrice',
 'beautiful',
 'beautifully',
 'beauty',
 'beckett',
 'bed',
 'bedelia',
 'bedroom',
 'beer',
 'began',
 'begin',
 'beginning',
 'beginnings',
 'begins',
 'begun',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believers',
 'believes',
 'believing',
 'bell',
 'beloved',
 'ben',
 'beneath',
 'benefits',
 'benjamin',
 'bent',
 'berlin',
 'bernard',
 'bertie',
 'beset',
 'best',
 'bestseller',
 'bestselling',
 'betrayal',
 'betrayals',
 'betrayed',
 'betsy',
 'better',
 'betty',
 'bible',
 'biblical',
 'bibliography',
 'big',
 'bigger',
 'biggest',
 'billionaire',
 'billy',
 'biographical',
 'biographies',
 'biography',
 'biological',
 'biologist',
 'biology',
 'bird',
 'birds',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarre',
 'black',
 'blake',
 'bleak',
 'blend',
 'blending',
 'blind',
 'bliss',
 'block',
 'blood',
 'bloody',
 'bloom',
 'blue',
 'blyton',
 'board',
 'boat',
 'bob',
 'bodies',
 'body',
 'bold',
 'boleyn',
 'bomb',
 'bond',
 'bonds',
 'bone',
 'bones',
 'bonus',
 'book',
 'books',
 'border',
 'bored',
 'borg',
 'borges',
 'boring',
 'born',
 'boss',
 'boston',
 'bought',
 'bound',
 'boundaries',
 'bounty',
 'bowles',
 'box',
 'boxed',
 'boy',
 'boyfriend',
 'boyhood',
 'boyle',
 'boys',
 'bradbury',
 'bradley',
 'brain',
 'brand',
 'brautigan',
 'brave',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breathtaking',
 'brian',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliance',
 'brilliant',
 'brilliantly',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'broad',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brutal',
 'brutally',
 'bryson',
 'buddhism',
 'buddhist',
 'budget',
 'buffett',
 'build',
 'building',
 'builds',
 'built',
 'bukowski',
 'bunny',
 'burgess',
 'buried',
 'burke',
 'burned',
 'burning',
 'burns',
 'burroughs',
 'burton',
 'bush',
 'business',
 'businessman',
 'busy',
 'buy',
 'cabot',
 'caesar',
 'cake',
 'california',
 'called',
 'calling',
 'calls',
 'calvin',
 'calvino',
 'cambridge',
 'came',
 'camera',
 'camp',
 'campaign',
 'campbell',
 'camps',
 'camus',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'candidate',
 'candy',
 'canon',
 'capable',
 'capacity',
 'cape',
 'capital',
 'capitalism',
 'capote',
 'captain',
 'capture',
 'captured',
 'captures',
 'capturing',
 'car',
 'card',
 'care',
 'career',
 'careers',
 'careful',
 'carefully',
 'carey',
 'caribbean',
 'caring',
 'carl',
 'carlos',
 'carnegie',
 'carol',
 'carolina',
 'caroline',
 'carolyn',
 'carrie',
 'carried',
 'carroll',
 'carry',
 'carrying',
 'carson',
 'carter',
 'cartoons',
 'carver',
 'case',
 'cases',
 'cash',
 'cast',
 'castaneda',
 'castle',
 'cat',
 'catch',
 'category',
 'catherine',
 'catholic',
 'cats',
 'caught',
 'cause',
 'caused',
 'causes',
 'cd',
 'celebrate',
 'celebrated',
 'celebrates',
 'celebration',
 'celebrity',
 'cell',
 'center',
 'centered',
 'centers',
 'central',
 'centre',
 'centuries',
 'century',
 'certain',
 'cervantes',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'challenging',
 'champion',
 'chance',
 'chandler',
 'change',
 'changed',
 'changes',
 'changing',
 'chaos',
 'chaotic',
 'chapter',
 'chapters',
 'character',
 'characteristic',
 'characteristics',
 'characters',
 'charge',
 'charged',
 'charges',
 'charismatic',
 'charles',
 'charlie',
 'charlotte',
 'charm',
 'charming',
 'charts',
 'chase',
 'chaucer',
 'cheap',
 'cheese',
 'chef',
 'chekhov',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chocolate',
 'choice',
 'choices',
 'chomsky',
 'choose',
 'chosen',
 'chris',
 'christ',
 'christian',
 'christianity',
 'christians',
 'christie',
 'christmas',
 'christopher',
 'chronicle',
 'chronicles',
 'chronicling',
 'chronology',
 'chuck',
 'church',
 'churchill',
 'cia',
 'cicero',
 'cider',
 'cinema',
 'circle',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civic',
 'civil',
 'civilization',
 'civilizations',
 'claim',
 'claims',
 'claire',
 'clan',
 'clancy',
 'clare',
 'clarissa',
 'clarity',
 'clark',
 'clarke',
 'clash',
 'class',
 'classes',
 'classic',
 'classical',
 'classics',
 'classroom',
 'clay',
 'clear',
 'clearly',
 'clegg',
 'clever',
 'client',
 'cliffsnotes',
 'climate',
 'climax',
 'clinic',
 'clive',
 'clock',
 'clone',
 'close',
 'closely',
 'closer',
 'closest',
 'club',
 'clubs',
 'clues',
 'coach',
 'coast',
 'code',
 'coelho',
 'cold',
 'cole',
 'colin',
 'collapse',
 'colleague',
 'colleagues',
 'collected',
 'collecting',
 'collection',
 'collections',
 'collective',
 'collector',
 'collects',
 'colleen',
 'college',
 'collins',
 'collision',
 'colonel',
 'colonial',
 'colony',
 'color',
 'colorful',
 'colour',
 'com',
 'combat',
 'combination',
 'combine',
 'combined',
 'combines',
 'combining',
 'come',
 'comedy',
 'comes',
 'comfortable',
 'comic',
 'comics',
 'coming',
 'command',
 'commander',
 'commentaries',
 'commentary',
 'comments',
 'commercial',
 'commission',
 'commissioned',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'communities',
 'community',
 'companies',
 'companion',
 'companions',
 'company',
 'compassion',
 'compassionate',
 'compelling',
 'compendium',
 'competition',
 'compilation',
 'compiled',
 'complement',
 'complemented',
 'complete',
 'completely',
 'complex',
 'complexity',
 'complicated',
 'composed',
 'composition',
 'comprehensive',
 'computer',
 'computers',
 'conan',
 'concentration',
 'concept',
 'concepts',
 'concern',
 'concerned',
 'concerning',
 'concerns',
 'concise',
 'conclusion',
 'conclusions',
 'concrete',
 'condition',
 'conditions',
 'conduct',
 'confessions',
 'confidence',
 'conflict',
 'conflicting',
 'conflicts',
 'confront',
 'confrontation',
 'confronted',
 'confronting',
 'confronts',
 'connected',
 'connection',
 'connections',
 'connor',
 'conrad',
 'conscience',
 'conscious',
 'consciousness',
 'consequences',
 'conservation',
 'consider',
 'consideration',
 'considered',
 'considers',
 'consistent',
 'consistently',
 'conspiracy',
 'constance',
 'constant',
 'constantine',
 'constantly',
 'constitution',
 'construction',
 'contain',
 'contained',
 'containing',
 'contains',
 'contemporaries',
 'contemporary',
 'content',
 'contents',
 'contest',
 'context',
 'continent',
 'continental',
 'continue',
 'continued',
 'continues',
 'continuing',
 'contrast',
 'contributed',
 'contribution',
 'contributions',
 'control',
 'controversial',
 'controversy',
 'conventional',
 'conversation',
 'conversations',
 'conveys',
 'convicted',
 'convinced',
 'convincing',
 'cook',
 'cookbook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'copies',
 'cops',
 'copy',
 'core',
 'cormac',
 'cornell',
 'corner',
 'corporate',
 'corporation',
 'corpse',
 'correct',
 'correspondence',
 'corrupt',
 'corruption',
 'cosmic',
 'cosmology',
 'cosmos',
 'cost',
 'costumes',
 'couldn',
 'council',
 'count',
 'counter',
 'countless',
 'countries',
 'country',
 'countryside',
 ...]

In [215]:
import nltk

In [216]:
#!pip install nltk

In [217]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [218]:
ps.stem("lovingly")

'lovingli'

In [219]:
# Creating a function stem to convert all the words into root words

def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [220]:
new_books['tag'][500]

'laura ingalls wilder juvenile fiction join the ingalls family as they celebrate little laura’s fifth birthday in the big woods of wisconsin. there are special presents from everyone, and that night laura falls asleep to the merry music of pa’s fiddle. renée graef’s enchanting full-color illustrations, inspired by garth williams’s classic artwork, bring laura and her family lovingly to life in our tenth my first little house book, adapted from laura ingalls wilder’s beloved storybooks. it’s a little house birthday to remember!'

In [221]:
# Checking the stemming

stem("laura ingalls wilder juvenile fiction join the ingalls family as they celebrate little laura’s fifth birthday in the big woods of wisconsin. there are special presents from everyone, and that night laura falls asleep to the merry music of pa’s fiddle. renée graef’s enchanting full-color illustrations, inspired by garth williams’s classic artwork, bring laura and her family lovingly to life in our tenth my first little house book, adapted from laura ingalls wilder’s beloved storybooks. it’s a little house birthday to remember!")

'laura ingal wilder juvenil fiction join the ingal famili as they celebr littl laura’ fifth birthday in the big wood of wisconsin. there are special present from everyone, and that night laura fall asleep to the merri music of pa’ fiddle. rené graef’ enchant full-color illustrations, inspir by garth williams’ classic artwork, bring laura and her famili lovingli to life in our tenth my first littl hous book, adapt from laura ingal wilder’ belov storybooks. it’ a littl hous birthday to remember!'

In [222]:
new_books['tag'] = new_books['tag'].apply(stem)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

## Repeating the above steps

In [223]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features =5000 , stop_words = 'english',ngram_range=(1, 2) )

In [224]:
# After stemming recreating vectorts

vectors = cv.fit_transform(new_books['tag']).toarray()

In [225]:
# Verifying

cv.get_feature_names()

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '000 printing',
 '10',
 '10 000',
 '100',
 '100 000',
 '11',
 '12',
 '12 500',
 '13',
 '14',
 '15',
 '15 000',
 '150',
 '16',
 '16 page',
 '17',
 '18',
 '1914',
 '1920s',
 '1929',
 '1930',
 '1940',
 '1945',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1962',
 '1970',
 '1980s',
 '1984',
 '1986',
 '1987',
 '1989',
 '1990',
 '1991',
 '1992',
 '1994',
 '1995',
 '1996',
 '1998',
 '1999',
 '19th',
 '20',
 '20 000',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2005',
 '20th',
 '20th century',
 '21',
 '21st',
 '21st century',
 '22',
 '24',
 '25',
 '25 000',
 '250',
 '250 000',
 '30',
 '30 000',
 '300',
 '300 000',
 '35',
 '35 000',
 '40',
 '40 000',
 '400',
 '50',
 '50 000',
 '500',
 '500 printing',
 '60',
 '75',
 '75 000',
 'aaron',
 'abandon',
 'abbey',
 'abbi',
 'abe',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abraham',
 'abroad',
 'absolut',
 'absorb',
 'abstract',
 'absurd',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'acclaim author',
 'accompani',
 'accomplish',
 'accord',
 'account',
 'account hi',
 'accur',
 'accus',
 'achiev',
 'acknowledg',
 'acquaint',
 'acquir',
 'act',
 'action',
 'activ',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adam fiction',
 'adams',
 'adapt',
 'add',
 'addict',
 'addit',
 'address',
 'administr',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'adult',
 'adult fiction',
 'adulteri',
 'adults',
 'advanc',
 'advantag',
 'adventur',
 'adventur stori',
 'adventure',
 'adventures',
 'advic',
 'aeschylu',
 'aeschylus',
 'aesthet',
 'affair',
 'affairs',
 'affect',
 'affirm',
 'afford',
 'afraid',
 'africa',
 'african',
 'african american',
 'aftermath',
 'afterword',
 'ag',
 'agatha',
 'agatha christi',
 'age',
 'agenc',
 'agent',
 'ages',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aids',
 'aim',
 'air',
 'al',
 'ala',
 'alan',
 'alan dean',
 'alanna',
 'albert',
 'album',
 'alchemist',
 'alcohol',
 'alcott',
 'aldou',
 'aldou huxley',
 'alex',
 'alexand',
 'alfr',
 'ali',
 'alic',
 'alice',
 'alien',
 'alighieri',
 'alik',
 'alike',
 'aliv',
 'alive',
 'allan',
 'allan poe',
 'allen',
 'alley',
 'alli',
 'allow',
 'alon',
 'alongsid',
 'alphabet',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'amano',
 'amateur',
 'amaz',
 'ambit',
 'ambiti',
 'ambition',
 'amelia',
 'america',
 'american',
 'american fiction',
 'american history',
 'americans',
 'ami',
 'amid',
 'amidst',
 'amus',
 'analys',
 'analysi',
 'analysis',
 'analyt',
 'analyz',
 'ancient',
 'ancient greec',
 'anderson',
 'andi',
 'andrea',
 'andrew',
 'anecdot',
 'anecdotes',
 'angel',
 'angela',
 'angela knight',
 'anger',
 'anguish',
 'ani',
 'anim',
 'animals',
 'anita',
 'ann',
 'ann rice',
 'anna',
 'anne',
 'anni',
 'anni dillard',
 'anniversari',
 'anniversari edit',
 'annot',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'answer question',
 'antholog',
 'anthoni',
 'anthoni fiction',
 'anti',
 'anticip',
 'antiqu',
 'anton',
 'anyon',
 'anyth',
 'apart',
 'apocalypt',
 'appar',
 'appeal',
 'appear',
 'appli',
 'applic',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'appropri',
 'april',
 'ar',
 'arab',
 'archaeologist',
 'architect',
 'architectur',
 'archiv',
 'arctic',
 'arden',
 'area',
 'aren',
 'argu',
 'argument',
 'aris',
 'aristocrat',
 'aristophanes',
 'aristotl',
 'aristotle',
 'arm',
 'armi',
 'armstrong',
 'army',
 'arrang',
 'array',
 'arrest',
 'arriv',
 'art',
 'art disciplin',
 'art thi',
 'arthur',
 'arthur conan',
 'articl',
 'articles',
 'artifact',
 'artist',
 'artists',
 'artwork',
 'asia',
 'asian',
 'asid',
 'asimov',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assess',
 'assign',
 'assist',
 'associ',
 'assort',
 'assum',
 'astonish',
 'astronomi',
 'asylum',
 'athen',
 'athenian',
 'athens',
 'atlant',
 'atmospher',
 'atom',
 'attack',
 'attacks',
 'attain',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'atwood',
 'audienc',
 'august',
 'augustin',
 'augustine',
 'aunt',
 'austen',
 'austen fiction',
 'auster',
 'australia',
 'authent',
 'author',
 'author comic',
 'author fiction',
 'author juvenil',
 'author life',
 'authorit',
 'authors',
 'autobiograph',
 'autobiographi',
 'autobiographi author',
 'autobiographi thi',
 'autobiographi trace',
 'autobiography',
 'avail',
 'available',
 'available reprint',
 'averag',
 'avoid',
 'await',
 'awaken',
 'awar',
 'award',
 'award win',
 'away',
 'awesom',
 'babi',
 'baby',
 'bach',
 'backdrop',
 'background',
 'background author',
 'bad',
 'baggins',
 'baker',
 'balanc',
 'baldwin',
 'ball',
 'ballet',
 'ban',
 'band',
 'bang',
 'banish',
 'bank',
 'bank fiction',
 'bar',
 'barbara',
 'bare',
 'bargain',
 'barker',
 'barn',
 'barri',
 'barth',
 'bas',
 'base',
 'basebal',
 'basi',
 'basic',
 'battl',
 'battle',
 'battlefield',
 'baudrillard',
 'baxter',
 'bay',
 'bc',
 'bce',
 'beach',
 'bear',
 'beast',
 'beat',
 'beatl',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'beckett',
 'becom',
 'becom involv',
 'becom target',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befor hi',
 'befriend',
 'began',
 'begin',
 'beginning',
 'begun',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believ',
 'bell',
 'belong',
 'belov',
 'ben',
 'beneath',
 'benefit',
 'benjamin',
 'bent',
 'berlin',
 'bernard',
 'berti',
 'beset',
 'besid',
 'best',
 'best book',
 'best friend',
 'best known',
 'best lov',
 'best sel',
 'best work',
 'bestsel',
 'bestsel author',
 'bestseller',
 'betray',
 'betrayal',
 'betsi',
 'betsy',
 'better',
 'betti',
 'bi',
 'bibl',
 'bible',
 'biblic',
 'bibliographi',
 'bibliography',
 'bid',
 'big',
 'bigger',
 'biggest',
 'billi',
 'biograph',
 'biographi',
 'biographi autobiographi',
 'biographical',
 'biography',
 'biolog',
 'biologist',
 'bird',
 'birds',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarr',
 'black',
 'black elk',
 'blackmail',
 'blake',
 'blame',
 'bleak',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloom',
 'blow',
 'blue',
 'blyton',
 'board',
 'boat',
 'bob',
 'bodi',
 'body',
 'body mind',
 'bold',
 'boleyn',
 'bomb',
 'bond',
 'bone',
 'book',
 'book award',
 'book contain',
 'book critic',
 'book ha',
 'book includ',
 'book jacket',
 'book review',
 'book tell',
 'book written',
 'book year',
 'books',
 'border',
 'bore',
 'borg',
 'born',
 'boss',
 'boston',
 'bought',
 'bound',
 'boundari',
 'bounti',
 'bounti hunter',
 'bowl',
 'box',
 'box set',
 'boy',
 'boyfriend',
 'boyhood',
 'boyl',
 'boys',
 'bradley',
 'brain',
 'branch',
 'brand',
 'brautigan',
 'brave',
 'break',
 'breakdown',
 'breath',
 'breathtak',
 'brian',
 'bride',
 'bridg',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'brilliantli',
 'bring',
 'bring hi',
 'bring life',
 'bring togeth',
 'brink',
 'britain',
 'british',
 'broad',
 'broke',
 'broken',
 'brook',
 'brooklyn',
 'brother',
 'brought',
 'brown',
 'brown fiction',
 'bruce',
 'brutal',
 'bryson',
 'buddhism',
 'buddhist',
 'budget',
 'build',
 'building',
 'built',
 'bukowski',
 'burgess',
 'buri',
 'burn',
 'burton',
 'bush',
 'busi',
 'busi econom',
 'business',
 'businessman',
 'butler',
 'buy',
 'cabot',
 'caesar',
 'cake',
 'cal',
 'california',
 'calvin',
 'cambridg',
 'came',
 'camera',
 'camp',
 'campaign',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canon',
 'capabl',
 'capac',
 'cape',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'card',
 'card fiction',
 'care',
 'career',
 'career hi',
 'carey',
 'caribbean',
 'carl',
 'carlo',
 'carlo castaneda',
 'carnegi',
 'carol',
 'carol oat',
 'carolin',
 'carolina',
 'carolyn',
 'carri',
 'carrol',
 'carson',
 'carter',
 'cartoon',
 'carver',
 'case',
 'case studi',
 'cases',
 'cash',
 'cast',
 'castaneda',
 'castl',
 'castle',
 'cat',
 'catch',
 'categori',
 'catherin',
 'cathol',
 'cathol church',
 'caught',
 'caus',
 'cave',
 'cd',
 'celebr',
 'cell',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'century thi',
 'certain',
 'cervantes',
 'chain',
 'challeng',
 'challenge',
 'champion',
 'chanc',
 'chance',
 'chandler',
 'chang',
 'chang life',
 'chang world',
 'change',
 'changed',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'charact analys',
 'charact map',
 'character',
 'characterist',
 'characters',
 'characters literari',
 'charg',
 'charismat',
 'charl',
 'charl bukowski',
 'charl dicken',
 'charli',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chaucer',
 'cheap',
 'chef',
 'chekhov',
 'cherish',
 'chicago',
 'chief',
 'child',
 'childhood',
 'childhood friend',
 'children',
 'children book',
 'children stori',
 'chill',
 'china',
 'chines',
 'chocol',
 'choic',
 'choice',
 'choices',
 'chomsky',
 'choos',
 'chosen',
 'chri',
 'christ',
 'christi',
 'christi detect',
 'christi fiction',
 'christian',
 'christianity',
 'christma',
 'christmas',
 'christoph',
 'christoph hitchen',
 'chronicl',
 'chronicl life',
 'chronolog',
 'chuck',
 'church',
 'cia',
 'cicero',
 'cider',
 'cinema',
 'circl',
 'circl award',
 'circumst',
 'cite',
 'citi',
 'cities',
 'citizen',
 'city',
 'civic',
 'civil',
 'civil right',
 'civil war',
 'civilization',
 'claim',
 'clair',
 'clan',
 'clanci',
 'clancy',
 'clare',
 'clarifi',
 'clarissa',
 'clark',
 'clark fiction',
 'clash',
 'class',
 'classic',
 'classic familiar',
 'classic literatur',
 'classic novel',
 'classic work',
 'classics',
 'classroom',
 'clean',
 'clear',
 'clearli',
 'clever',
 'client',
 'cliffsnot',
 'cliffsnot studi',
 'climat',
 'climax',
 'climb',
 'clinic',
 'clive',
 'clive cussler',
 'clock',
 'clone',
 'close',
 'closer',
 'closest',
 'club',
 'clue',
 'coach',
 'coast',
 'code',
 'coelho',
 'coelho fiction',
 'coincid',
 'cold',
 'cole',
 'colin',
 'collabor',
 'collaps',
 'colleagu',
 'collect',
 'collect essay',
 'collect includ',
 'collect short',
 'collect stori',
 'collect stories',
 'collect thi',
 'collection',
 'collector',
 'colleg',
 'college',
 'collin',
 'collins',
 'colonel',
 'coloni',
 'color',
 'colour',
 'column',
 'com',
 'combat',
 'combin',
 'come',
 'come age',
 'come term',
 'come true',
 'comedi',
 'comedy',
 'comfort',
 'comic',
 'comic graphic',
 'coming',
 'command',
 'comment',
 'commentari',
 'commentari major',
 'commentary',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communities',
 'community',
 'compani',
 'companion',
 'company',
 'compar',
 'compass',
 'compassion',
 'compel',
 'compendium',
 'compet',
 'competit',
 'compil',
 'complement',
 'complement classic',
 'complet',
 'complet text',
 'complete',
 'complex',
 'complic',
 'compos',
 'comprehens',
 'compris',
 'compromis',
 'comput',
 'conan',
 'conceiv',
 'concentr',
 'concept',
 'concern',
 'concis',
 'conclud',
 'conclus',
 'concret',
 'condemn',
 'condit',
 'conduct',
 'confess',
 'confid',
 'conflict',
 'confront',
 'confront hi',
 'confus',
 'congreg',
 'connect',
 'connor',
 'conquer',
 'conrad',
 'conscious',
 'consciousness',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'consider',
 'consist',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'constitut',
 'construct',
 'consult',
 'consum',
 'contain',
 'contemporari',
 'contemporari fiction',
 'contend',
 'content',
 'contest',
 'context',
 'contin',
 'continent',
 'continu',
 'continu hi',
 'contrast',
 'contribut',
 'control',
 'controversi',
 'conveni',
 'convent',
 'convers',
 'convey',
 'convict',
 'convinc',
 'cook',
 'cookbook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'copi',
 'copies',
 'copyright',
 'core',
 'cormac',
 'cormac mccarthi',
 'cornel',
 'corner',
 'corpor',
 'corps',
 'correct',
 'correspond',
 'corrupt',
 'cosmic',
 'cosmolog',
 'cost',
 'costum',
 'couldn',
 'council',
 'count',
 ...]

In [226]:
len(vectors)

6548

In [227]:
vectors.shape

(6548, 5000)

We will now calculate the cosine distance(angular distance) not the euclidean distance(which is tip to tip).In higher dimension, euclidean distance is not a good measure.Distance is always inversally proportional to similarity.Distance less means similarity more and viceversa.

In [228]:
from sklearn.metrics.pairwise import cosine_similarity

In [229]:
# Getting the cosine similarity of vectors to see how close they are

cosine_similarity(vectors)

array([[1.        , 0.0309599 , 0.02028602, ..., 0.25642574, 0.07699276,
        0.0381108 ],
       [0.0309599 , 1.        , 0.02034892, ..., 0.07349167, 0.07021046,
        0.01911448],
       [0.02028602, 0.02034892, 1.        , ..., 0.        , 0.02300219,
        0.        ],
       ...,
       [0.25642574, 0.07349167, 0.        , ..., 1.        , 0.11630378,
        0.09046625],
       [0.07699276, 0.07021046, 0.02300219, ..., 0.11630378, 1.        ,
        0.        ],
       [0.0381108 , 0.01911448, 0.        , ..., 0.09046625, 0.        ,
        1.        ]])

In [230]:
similarity = cosine_similarity(vectors)

In [231]:
similarity[0]

array([1.        , 0.0309599 , 0.02028602, ..., 0.25642574, 0.07699276,
       0.0381108 ])

In [232]:
# enumerated(to keep the mapping - 1st book similarity with 2, 1st book similarity with 3 and so on in place) 
# Sorting the list of books to get the highrest similarity in descending order 
# x[1] : signifies sorting on the similarity score not the index
# getting the top 5

sorted(list(enumerate(similarity[0])),reverse = True,key = lambda x: x[1])[1:6]

[(4181, 0.5060427962483679),
 (4306, 0.4763849587291911),
 (4615, 0.4731064705859433),
 (1869, 0.46848557928420426),
 (2044, 0.45399627386325797)]

In [233]:
# Creating the recommend function which takes in title of the book and returns the similar books and similarity scores

def recommend_old(book):
    matches = new_books[new_books['title'] == book]
    if matches.empty:
        print(f"Book title '{book}' not found in the dataset.")
        return

    book_index = new_books[new_books['title'] == book].index[0]
    distances = similarity[book_index]
    books_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x: x[1])[1:6]
    
    for i  in books_list:
        
        #print(new_books.iloc[i[0]].title)
        score = i[1]
        title = new_books.iloc[i[0]].title 
        print(f"{title} - similarity score: {score:.3f}")

In [234]:
# Creating the recommend function which takes in title of the book and returns the similar books and similarity scores

def recommend(book):
    matches = new_books[new_books['title'] == book]
    if matches.empty:
        print(f"Book title '{book}' not found in the dataset.")
        return

    book_index = matches.index[0]
    distances = similarity[book_index]
    books_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x: x[1])[1:6]
    
    for i  in books_list:
        # Get index of recommended book
        rec_index=i[0]
        # Get title and isbn from the dataframe
        title = new_books.iloc[rec_index].title
        isbn = new_books.iloc[rec_index].isbn13
        #print(new_books.iloc[i[0]].title)
        score = i[1]
        #title = new_books.iloc[i[0]].title 
        print(f"{title},{isbn} - similarity score: {score:.3f}")

In [168]:
matches = new_books[new_books['title'] == 'Gilead']
if matches.empty:
    print(f"Book title '{book}' not found in the dataset.")


book_index = matches.index[0]
print("book_index",book_index)
distances = similarity[book_index]
books_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x: x[1])[1:6]
print("book_list",books_list)
 
print('test')
for i  in books_list:
    
        # Get index of recommended book
    rec_index=i[0]
    print(rec_index)
        # Get title and isbn from the dataframe
    title = new_books.iloc[rec_index].title
    isbn = new_books.iloc[rec_index].isbn13
    #print(new_books.iloc[i[0]].title)
    score = i[1]
    #title = new_books.iloc[i[0]].title 
    print(f"{title},{isbn} - similarity score: {score:.3f}")

book_index 0
book_list [(4178, 0.5060427962483679), (4302, 0.4763849587291911), (4611, 0.4731064705859433), (1868, 0.46848557928420426), (2043, 0.45399627386325797)]
test
4178
Man and Boy,9780740000000.0 - similarity score: 0.506
4302
The Languages of Pao,9780740000000.0 - similarity score: 0.476
4611
For the Sins of My Father,9780770000000.0 - similarity score: 0.473
1868
Until I Find You,9780350000000.0 - similarity score: 0.468
2043
John James Audubon,9780380000000.0 - similarity score: 0.454

In [235]:
new_books[new_books['title'] == 'I Am that'].index[0]

6545

In [236]:
new_books

,isbn13,title,tag
0,9780002005883,Gilead,marilynn robinson fiction a novel that reader ...
1,9780002261982,Spider's Web,charl osborne;agatha christi detect and myster...
2,9780006163831,The One Tree,stephen r. donaldson american fiction volum tw...
3,9780006178736,Rage of angels,"sidney sheldon fiction a memorable, mesmer her..."
4,9780006280897,The Four Loves,clive stapl lewi christian life lewis' work on...
...,...,...,...
6543,9788173031014,Journey to the East,hermann hess adventur stori thi book tell the ...
6544,9788179921623,The Monk Who Sold His Ferrari: A Fable About F...,robin sharma health & fit wisdom to creat a li...
6545,9788185300535,I Am that,sri nisargadatta maharaj;sudhakar s. dikshit p...
6546,9789027712059,The Berlin Phenomenology,georg wilhelm friedrich hegel histori sinc the...
6547,9789042003408,'I'm Telling You Stories',helena grice;tim wood literari critic thi is a...

In [237]:
# Testing

recommend("Gilead")

Man and Boy,9780743225083 - similarity score: 0.506
The Languages of Pao,9780743487146 - similarity score: 0.476
For the Sins of My Father,9780767906890 - similarity score: 0.473
Until I Find You,9780345479723 - similarity score: 0.468
John James Audubon,9780375713934 - similarity score: 0.454

In [138]:
import pickle

In [73]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [238]:
pickle.dump(new_books.to_dict(),open('data.pkl','wb'))